notifications:
  email: false
  slack: inkpebble:E4ZgOJD6kJyY8JTl0Rrnyhno
language: python
python: 
- "2.7"
install: "pip install -r requirements/local.txt"
env:
- CAH_KEY="shhthisisasecret"
script: "python manage.py test cards --settings=cah.settings.test"
deploy:
  provider: heroku
  api_key:
    secure: "iAblHa9zb7mcNqcz/JV1mtzNfreB7fAtf09ML1NEwzjOieJnQGPZU7eB1qwziUllGVCUT9iExXUc9mJJZ0gDRbwK6HZf5MGa9kjeDAzsy15KORvj2tkv9OASCdTYuappOYAw1EVEdAuaNrkKak4STKeWAICdEjiSYiX5/d+3rVg="
  app: tintg-stage
  strategy: git
  on:
    repo: phildini/cards-against-django
