notifications: 
  slack: inkpebble:E4ZgOJD6kJyY8JTl0Rrnyhno
language: python
python: 
- "2.7"
install: "pip install -r requirements/local.txt"
env:
- CAH_KEY="shhthisisasecret"
script: "python manage.py test cards --settings=cah.settings.test"
deploy:
  provider: heroku
  api_key:
    secure: KPdJ2AcC5JZYhV+RnqUIzUhYtAoD2I5oXAfm3j0dzifPCzkgF1eBevjVGDfwwj80f6qWSsxBgMeniMsUqWEUTkryM99ifsHS5LlXCzZ9nWkjK1gfFW+3h+X6bog2RkAOp60sdsZmyIiasfFiVo72vuIlDG3km3WO53jMWnrnpD8=
  app: tintg-stage
  strategy: git
  on:
    repo: phildini/cards-against-django
